[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  name = "github.com/go-xorm/xorm"
  version = "0.7.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"
